### ISSUE TITLE
Question about the use of `MutationObserver` for namespace isolation

### ISSUE THREAD

**Issue by ericcornelissen** [SoheilKhodayari/DOMClobbering#10]
The [Patterns & Guidelines Wiki page](https://domclob.xyz/domc_wiki/indicators/patterns.html#namespace-isolation) [currently](https://github.com/SoheilKhodayari/DOMClobbering/blob/ed808a345911ecb9bbb81624c59d13b8d00b758e/domc_wiki/indicators/patterns.md#namespace-isolation) states:

> **Namespace Isolation**
> While robust sanitizers may remove [named properties](https://webidl.spec.whatwg.org/#dfn-support-named-properties), an alternative solution is to separate the namespace of variables defined by JavaScript code and named properties in user-generated markups. For example, the markdown to HTML converter of source code version control applications often prefix id and name attribute values of user-generated markup with a specific string. Motivated by this solution, one can monitor runtime changes in the DOM tree via the [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), and prefix named properties of all dynamically inserted markups before adding them to the tree, which patches all aforementioned vulnerable patterns.

I tried to implement the suggested [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to prefix [named properties](https://webidl.spec.whatwg.org/#idl-named-properties) of all dynamically inserted markups before they're added to the tree. What I understand this to mean is that a `MutationObserver` is set up early in the page load, changing the `id` and `name` of all `HTMLElement`s on the fly to prevent clobbering. My MutationObserver implementation is included as a snippet below.

For the implementation I created, it works as expected for "static HTML" (HTML element included in the initial document) but does not work as expected for dynamically added HTML. For the former the `id`/`name` is changed and clobbering is prevented, but for the latter - even though the `id`/`name` is changed - clobbering is not entirely prevented. (I have tested it in Chrome 129 and Firefox 115.) A preview is available at <https://dom-clobbering-mutation-observer.glitch.me/>.

Can you elaborate on this behavior? If this is expected, I believe the guideline may be misleading for readers. If this is not expected and there exists a MutationObserver implementation that does work properly, I think it would be very valuable for you to share it.

---

```javascript
const mo = new MutationObserver((records, _self) => {
  for (const record of records) {
    switch (record.type) {
    case "childList":
      for (const node of record.addedNodes) {
        if (!(node instanceof HTMLElement)) continue;
        
        const id = node.getAttribute("id");
        if (id !== null) {
          node.setAttribute("id", `id_prefix_${id}`);
        }
        
        const name = node.getAttribute("name");
        if (name !== null) {
          node.setAttribute("name", `name_prefix_${name}`);
        }
      }
      break;
    }
  }
});

mo.observe(document.body, {
  subtree: true,
  childList: true,
});
```

**Comment by SoheilKhodayari** [comment]
Hi @ericcornelissen, 

Thank you for opening up this issue and sharing your code! I think it demonstrates the main concept nicely. For a more comprehensive implementation catching potential edge cases, you might want to check out this repository: [Shield](https://github.com/weizman/shield).

I think the behavior you’re seeing is due to timing issues. Specifically, it looks like `document[id]` is logged before the Mutation Observer has a chance to update the `id` or `name`. For example, if you open your browser console in the link you provided and log `document.close` again (after dynamically adding an element with `id=close`), you’ll see it’s not clobbered.

<img width="687" alt="Screenshot 2024-11-05 at 16 58 08" src="https://github.com/user-attachments/assets/388e6022-da59-48f6-ba81-669f92078cff">


That said, while the Mutation Observer approach helps, it doesn't fully eliminate DOM clobbering. For instance, if a script is injected before the monitoring script, it could bypass this protection. Some newer iframe techniques might also sidestep it. Improving this part in the guideline text would be of course helpful, and I appreciate a PR. 

PS: another option for protection is namespace isolation during HTML sanitization. See, e.g., [DOMPurify](https://github.com/cure53/DOMPurify/pull/710).

**Comment by ericcornelissen** [comment]
> Thank you for opening up this issue and sharing your code! I think it demonstrates the main concept nicely. For a more comprehensive implementation catching potential edge cases, you might want to check out this repository: [Shield](https://github.com/weizman/shield).

Cool, thanks for sharing 🙂 That does look a bit more comprehensive than what I cobbled together.


> I think the behavior you’re seeing is due to timing issues. Specifically, it looks like `document[id]` is logged before the Mutation Observer has a chance to update the `id` or `name`. For example, if you open your browser console in the link you provided and log `document.close` again (after dynamically adding an element with `id=close`), you’ll see it’s not clobbered.

Yes, I did realize this is the case and should have probably mentioned it in my comment. However, this seems like quite an important gap which could allow for bypasses in some realistic scenarios (e.g. reading from `document` right after adding untrusted HTML) that's very easy to miss.


> That said, while the Mutation Observer approach helps, it doesn't fully eliminate DOM clobbering. For instance, if a script is injected before the monitoring script, it could bypass this protection. Some newer iframe techniques might also sidestep it. Improving this part in the guideline text would be of course helpful, and I appreciate a PR.

I'll try to submit something to expand and improve the text. 


> PS: another option for protection is namespace isolation during HTML sanitization. See, e.g., [DOMPurify](https://github.com/cure53/DOMPurify/pull/710).

Would it make sense to add this too?

**Comment by SoheilKhodayari** [comment]
> I'll try to submit something to expand and improve the text.

Great, thanks a lot! 


> Would it make sense to add this too?

Sure!
